/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.File;
import javax.swing.ImageIcon;
import Mosaic.*;
import Mosaic.Mosaic.SelectAlgorithm;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.core.Point;
import org.opencv.core.Scalar;
import org.opencv.highgui.Highgui;

/**
 * Main window of application. Provides almost all functionality on 3 tabs.
 * 
 * @author Marek Zuzi
 */
public class PhotomosaicWindow extends javax.swing.JFrame implements PropertyChangeListener {

    private Mosaic m;
    private Tileset t;
    private ResourceBundle strings;
    private ImageCanvas canvas;

    /**
     * Creates new form NewApplication
     */
    public PhotomosaicWindow() {
        initComponents();
        
        m = new Mosaic();
        m.setxTiles((int)spin_xTiles.getValue());
        m.setyTiles((int)spin_yTiles.getValue());
        m.setTileWidth((int)spin_tileWidth.getValue());
        m.setTileHeight((int)spin_tileHeight.getValue());
        m.addPropertyChangeListener(this);

        t = new Tileset();
        table_step2Preview.setModel(t);
        
        strings = ResourceBundle.getBundle("Resources/Strings");
        
        canvas = new ImageCanvas();
        jScrollPane2.getViewport().add(canvas);

        aboutDialog.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        openFileDialog = new javax.swing.JFileChooser();
        saveFileDialog = new javax.swing.JFileChooser();
        openDirDialog = new javax.swing.JFileChooser();
        aboutDialog = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        matchingButGrp = new javax.swing.ButtonGroup();
        blendBtnGrp = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        centralTabPane = new javax.swing.JTabbedPane();
        step1panel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        label_step1preview = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        but_step1browse = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        but_step1next = new javax.swing.JButton();
        but_step1loadSaved = new javax.swing.JButton();
        step2panel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        scrollPane_step2preview = new javax.swing.JScrollPane();
        table_step2Preview = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        but_step2addFile = new javax.swing.JButton();
        but_step2remove = new javax.swing.JButton();
        label_step2count = new javax.swing.JLabel();
        but_step2addVideo = new javax.swing.JButton();
        but_step2addFolder = new javax.swing.JButton();
        but_step2next = new javax.swing.JButton();
        but_step2removeAll = new javax.swing.JButton();
        step3panel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        but_step3preview = new javax.swing.JButton();
        but_step3save = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        rb_selectRand = new javax.swing.JRadioButton();
        rb_selectColor = new javax.swing.JRadioButton();
        rb_selectMatch = new javax.swing.JRadioButton();
        box_avoidRep = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        spin_xTiles = new javax.swing.JSpinner();
        spin_yTiles = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        spin_tileWidth = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        spin_tileHeight = new javax.swing.JSpinner();
        but_step3saveSett = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        slider_blendAmount = new javax.swing.JSlider();
        rb_blendNoblend = new javax.swing.JRadioButton();
        rb_blendColor = new javax.swing.JRadioButton();
        rb_blendOriginal = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        label_progress = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        openFileDialog.setFileFilter(new ImageFileFilter());

        saveFileDialog.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        saveFileDialog.setFileFilter(new ImageFileFilter());

        openDirDialog.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Resources/Strings"); // NOI18N
        aboutDialog.setTitle(bundle.getString("about")); // NOI18N
        aboutDialog.setResizable(false);

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/obr.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane3.setBorder(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(javax.swing.UIManager.getDefaults().getColor("Label.background"));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText(bundle.getString("aboutText")); // NOI18N
        jTextArea1.setBorder(null);
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout aboutDialogLayout = new javax.swing.GroupLayout(aboutDialog.getContentPane());
        aboutDialog.getContentPane().setLayout(aboutDialogLayout);
        aboutDialogLayout.setHorizontalGroup(
            aboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(261, 261, 261))
        );
        aboutDialogLayout.setVerticalGroup(
            aboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(bundle.getString("appName")); // NOI18N

        centralTabPane.setName(""); // NOI18N

        jLabel4.setText(bundle.getString("step1title")); // NOI18N

        jScrollPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jScrollPane1ComponentResized(evt);
            }
        });

        label_step1preview.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(label_step1preview);

        but_step1browse.setText(bundle.getString("browse")); // NOI18N
        but_step1browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_step1browseActionPerformed(evt);
            }
        });

        jLabel5.setText(bundle.getString("chooseFile")); // NOI18N

        but_step1next.setText(bundle.getString("next")); // NOI18N
        but_step1next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_step1nextActionPerformed(evt);
            }
        });

        but_step1loadSaved.setText(bundle.getString("loadSettings")); // NOI18N
        but_step1loadSaved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_step1loadSavedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(but_step1loadSaved, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(but_step1browse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(but_step1next)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(but_step1browse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(but_step1loadSaved)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 421, Short.MAX_VALUE)
                .addComponent(but_step1next)
                .addContainerGap())
        );

        javax.swing.GroupLayout step1panelLayout = new javax.swing.GroupLayout(step1panel);
        step1panel.setLayout(step1panelLayout);
        step1panelLayout.setHorizontalGroup(
            step1panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(step1panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(step1panelLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(172, 172, 172))
        );
        step1panelLayout.setVerticalGroup(
            step1panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(step1panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(step1panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        centralTabPane.addTab(bundle.getString("step1"), step1panel); // NOI18N

        jLabel6.setText(bundle.getString("step2title")); // NOI18N

        scrollPane_step2preview.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        table_step2Preview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table_step2Preview.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table_step2Preview.setCellSelectionEnabled(true);
        table_step2Preview.setFillsViewportHeight(true);
        table_step2Preview.setRowHeight(120);
        table_step2Preview.setRowMargin(5);
        table_step2Preview.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table_step2Preview.setShowHorizontalLines(false);
        table_step2Preview.setShowVerticalLines(false);
        table_step2Preview.setTableHeader(null);
        scrollPane_step2preview.setViewportView(table_step2Preview);

        but_step2addFile.setText(bundle.getString("addFile")); // NOI18N
        but_step2addFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_step2addFileActionPerformed(evt);
            }
        });

        but_step2remove.setText(bundle.getString("remove")); // NOI18N
        but_step2remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_step2removeActionPerformed(evt);
            }
        });

        label_step2count.setText(bundle.getString("tileCount")); // NOI18N

        but_step2addVideo.setText(bundle.getString("addVideo")); // NOI18N
        but_step2addVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_step2addVideoActionPerformed(evt);
            }
        });

        but_step2addFolder.setText(bundle.getString("addFolder")); // NOI18N
        but_step2addFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_step2addFolderActionPerformed(evt);
            }
        });

        but_step2next.setText("next");
        but_step2next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_step2nextActionPerformed(evt);
            }
        });

        but_step2removeAll.setText(bundle.getString("removeAll")); // NOI18N
        but_step2removeAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_step2removeAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(but_step2addFolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(but_step2addFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(but_step2addVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(but_step2remove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(but_step2next))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(label_step2count, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addComponent(but_step2removeAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(but_step2addFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(but_step2addFolder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(but_step2addVideo)
                .addGap(29, 29, 29)
                .addComponent(but_step2remove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_step2count)
                .addGap(18, 18, 18)
                .addComponent(but_step2removeAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(but_step2next)
                .addContainerGap())
        );

        javax.swing.GroupLayout step2panelLayout = new javax.swing.GroupLayout(step2panel);
        step2panel.setLayout(step2panelLayout);
        step2panelLayout.setHorizontalGroup(
            step2panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(step2panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane_step2preview, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(step2panelLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(140, 140, 140))
        );
        step2panelLayout.setVerticalGroup(
            step2panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(step2panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(step2panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPane_step2preview, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE))
                .addContainerGap())
        );

        centralTabPane.addTab(bundle.getString("step2"), step2panel); // NOI18N

        jLabel7.setText(bundle.getString("step3title")); // NOI18N

        jScrollPane4.setBorder(null);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        but_step3preview.setText(bundle.getString("previewMosaic")); // NOI18N
        but_step3preview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_step3previewActionPerformed(evt);
            }
        });

        but_step3save.setText(bundle.getString("saveMosaic")); // NOI18N
        but_step3save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_step3saveActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("matchAlgorithm"))); // NOI18N

        matchingButGrp.add(rb_selectRand);
        rb_selectRand.setText(bundle.getString("random")); // NOI18N
        rb_selectRand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_selectRandActionPerformed(evt);
            }
        });

        matchingButGrp.add(rb_selectColor);
        rb_selectColor.setSelected(true);
        rb_selectColor.setText(bundle.getString("matchColor")); // NOI18N
        rb_selectColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_selectColorActionPerformed(evt);
            }
        });

        matchingButGrp.add(rb_selectMatch);
        rb_selectMatch.setText(bundle.getString("matchPattern")); // NOI18N
        rb_selectMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_selectMatchActionPerformed(evt);
            }
        });

        box_avoidRep.setText(bundle.getString("avoidRep")); // NOI18N
        box_avoidRep.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                box_avoidRepStateChanged(evt);
            }
        });
        box_avoidRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_avoidRepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_selectRand)
                    .addComponent(rb_selectColor)
                    .addComponent(rb_selectMatch)
                    .addComponent(box_avoidRep))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rb_selectRand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_selectColor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_selectMatch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box_avoidRep))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("mosaicDims"))); // NOI18N

        spin_xTiles.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(10), Integer.valueOf(1), null, Integer.valueOf(1)));
        spin_xTiles.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin_xTilesStateChanged(evt);
            }
        });

        spin_yTiles.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(10), Integer.valueOf(1), null, Integer.valueOf(1)));
        spin_yTiles.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin_yTilesStateChanged(evt);
            }
        });

        jLabel2.setText(bundle.getString("xTiles")); // NOI18N

        jLabel3.setText(bundle.getString("yTiles")); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spin_yTiles, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(spin_xTiles))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spin_xTiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spin_yTiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("outputDims"))); // NOI18N

        spin_tileWidth.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(20), Integer.valueOf(1), null, Integer.valueOf(1)));
        spin_tileWidth.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin_tileWidthStateChanged(evt);
            }
        });

        jLabel10.setText(bundle.getString("width")); // NOI18N

        jLabel11.setText(bundle.getString("height")); // NOI18N

        spin_tileHeight.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(20), Integer.valueOf(1), null, Integer.valueOf(1)));
        spin_tileHeight.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin_tileHeightStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spin_tileWidth, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(spin_tileHeight))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(spin_tileWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(spin_tileHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        but_step3saveSett.setText(bundle.getString("saveSettings")); // NOI18N
        but_step3saveSett.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_step3saveSettActionPerformed(evt);
            }
        });

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("blending"))); // NOI18N

        slider_blendAmount.setMajorTickSpacing(50);
        slider_blendAmount.setMinorTickSpacing(5);
        slider_blendAmount.setPaintLabels(true);
        slider_blendAmount.setPaintTicks(true);
        slider_blendAmount.setSnapToTicks(true);
        slider_blendAmount.setToolTipText(bundle.getString("blendAmount")); // NOI18N
        slider_blendAmount.setEnabled(false);
        slider_blendAmount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_blendAmountStateChanged(evt);
            }
        });

        blendBtnGrp.add(rb_blendNoblend);
        rb_blendNoblend.setSelected(true);
        rb_blendNoblend.setText(bundle.getString("noBlend")); // NOI18N
        rb_blendNoblend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_blendNoblendActionPerformed(evt);
            }
        });

        blendBtnGrp.add(rb_blendColor);
        rb_blendColor.setText(bundle.getString("blendColor")); // NOI18N
        rb_blendColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_blendColorActionPerformed(evt);
            }
        });

        blendBtnGrp.add(rb_blendOriginal);
        rb_blendOriginal.setText(bundle.getString("blendOriginal")); // NOI18N
        rb_blendOriginal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_blendOriginalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slider_blendAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_blendOriginal)
                            .addComponent(rb_blendColor)
                            .addComponent(rb_blendNoblend))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rb_blendNoblend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_blendColor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_blendOriginal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(slider_blendAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(but_step3save, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(but_step3preview, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(but_step3saveSett, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(but_step3preview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(but_step3save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(but_step3saveSett)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(jPanel2);

        javax.swing.GroupLayout step3panelLayout = new javax.swing.GroupLayout(step3panel);
        step3panel.setLayout(step3panelLayout);
        step3panelLayout.setHorizontalGroup(
            step3panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(step3panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(step3panelLayout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(131, 131, 131))
        );
        step3panelLayout.setVerticalGroup(
            step3panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(step3panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(11, 11, 11)
                .addGroup(step3panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE))
                .addContainerGap())
        );

        centralTabPane.addTab(bundle.getString("step3"), step3panel); // NOI18N

        jPanel5.setMaximumSize(new java.awt.Dimension(173, 20));
        jPanel5.setMinimumSize(new java.awt.Dimension(173, 20));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_progress)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_progress))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(centralTabPane)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(centralTabPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText(bundle.getString("file")); // NOI18N

        openMenuItem.setMnemonic('o');
        openMenuItem.setText(bundle.getString("loadSettings")); // NOI18N
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText(bundle.getString("saveSettings")); // NOI18N
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        jMenuItem1.setText(bundle.getString("saveMosaic")); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem1);
        fileMenu.add(jSeparator1);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText(bundle.getString("exit")); // NOI18N
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText(bundle.getString("telp")); // NOI18N

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText(bundle.getString("about")); // NOI18N
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void spin_xTilesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin_xTilesStateChanged
        if(m.getImg() == null) return;
        
        m.setxTiles((int) spin_xTiles.getValue());
        paintGrid(m.getxTiles(), m.getyTiles());
    }//GEN-LAST:event_spin_xTilesStateChanged

    private void spin_yTilesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin_yTilesStateChanged
        if(m.getImg() == null) return;
        
        m.setyTiles((int) spin_yTiles.getValue());
        paintGrid(m.getxTiles(), m.getyTiles());
    }//GEN-LAST:event_spin_yTilesStateChanged

    private void but_step3previewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_step3previewActionPerformed
        if(m.getImg() == null) {
            JOptionPane.showMessageDialog(this, strings.getString("noImage"));
            return;
        }
        if(t.getRowCount()==0) {
            JOptionPane.showMessageDialog(this, strings.getString("noTiles"));
            return;
        }
        
        // create mosaic and display result in preview window
        label_progress.setText("Vytvara sa mozaika.");
        MosaicAssembler worker = new MosaicAssembler(m,t);
        worker.setDisplayCanvas(canvas);
        worker.setStatusLabel(label_progress);
        worker.execute();
    }//GEN-LAST:event_but_step3previewActionPerformed

    private void but_step1nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_step1nextActionPerformed
        centralTabPane.setSelectedIndex(1);
    }//GEN-LAST:event_but_step1nextActionPerformed

    private void but_step1browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_step1browseActionPerformed
        // display file choose dialog
        int retVal = openFileDialog.showOpenDialog(centralTabPane);
        if (retVal == JFileChooser.APPROVE_OPTION) {
            File f = openFileDialog.getSelectedFile();
            Mat img = ImageUtils.loadImage(f);
            if (img.empty()) {
                JOptionPane.showMessageDialog(this, strings.getString("cantLoad"), strings.getString("loadError"), JOptionPane.ERROR_MESSAGE);
                return;
            }
            m.setImg(img);
            
            double wRatio = jScrollPane1.getWidth()/(double)img.width();
            double hRatio = jScrollPane1.getHeight()/(double)img.height();
            
            label_step1preview.setIcon(ImageUtils.createIcon(img, Math.min(wRatio, hRatio)));
            canvas.setImage(img);
        }
    }//GEN-LAST:event_but_step1browseActionPerformed

    private void but_step3saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_step3saveActionPerformed
        if (m.getResult() == null) {
            JOptionPane.showMessageDialog(centralTabPane, "No result to save!");
            return;
        }
        int retVal = saveFileDialog.showSaveDialog(centralTabPane);
        if (retVal == JFileChooser.APPROVE_OPTION) {
            String path = saveFileDialog.getSelectedFile().getPath();
            if(!saveFileDialog.getFileFilter().accept(saveFileDialog.getSelectedFile())) {
                path = path + ".jpg";
            }
            if(!Highgui.imwrite(path, m.getResult())) {
                try {
                    ImageIO.write(ImageUtils.mat2image(m.getResult()), "jpg", saveFileDialog.getSelectedFile());
                } catch (IOException ex) {
                    Logger.getLogger(PhotomosaicWindow.class.getName()).log(Level.SEVERE, "mosaic could not be saved", ex);
                }
            }
        }
    }//GEN-LAST:event_but_step3saveActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // show about message box
        aboutDialog.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        aboutDialog.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jScrollPane1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jScrollPane1ComponentResized
        if(m == null) return;
        Mat img = m.getImg();
        if(img == null) return;
        
        double wRatio = jScrollPane1.getWidth()/(double)img.width();
        double hRatio = jScrollPane1.getHeight()/(double)img.height();
        
        label_step1preview.setIcon(ImageUtils.createIcon(img, Math.min(wRatio, hRatio)));
    }//GEN-LAST:event_jScrollPane1ComponentResized

    private void box_avoidRepStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_box_avoidRepStateChanged
        m.setAvoidRep(box_avoidRep.isSelected());
    }//GEN-LAST:event_box_avoidRepStateChanged

    private void slider_blendAmountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_blendAmountStateChanged
        if(!slider_blendAmount.getValueIsAdjusting()) {
            m.setBlendAmount((int)slider_blendAmount.getValue());
        }
    }//GEN-LAST:event_slider_blendAmountStateChanged

    private void spin_tileWidthStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin_tileWidthStateChanged
        m.setTileWidth((int)spin_tileWidth.getValue());
    }//GEN-LAST:event_spin_tileWidthStateChanged

    private void spin_tileHeightStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin_tileHeightStateChanged
        m.setTileHeight((int)spin_tileHeight.getValue());
    }//GEN-LAST:event_spin_tileHeightStateChanged

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        this.but_step1loadSavedActionPerformed(evt);
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void but_step2nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_step2nextActionPerformed
        centralTabPane.setSelectedIndex(2);
    }//GEN-LAST:event_but_step2nextActionPerformed

    private void but_step2addFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_step2addFolderActionPerformed
        // display folder choose dialog and add folder to tileset
        int retVal = openDirDialog.showOpenDialog(centralTabPane);
        if (retVal == JFileChooser.APPROVE_OPTION) {
            TileLoader worker = new TileLoader();
            worker.setFile(openDirDialog.getSelectedFile());
            worker.setUpdateLabel(label_progress);
            worker.setCountLabel(label_step2count);
            worker.setTileset(t);
            worker.setButton(but_step2addFolder);
            worker.addPropertyChangeListener(this);
            but_step2addFolder.setEnabled(false);
            label_progress.setText(strings.getString("loadingDir") + openDirDialog.getSelectedFile().getName());
            worker.execute();
        }
    }//GEN-LAST:event_but_step2addFolderActionPerformed

    private void but_step2addVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_step2addVideoActionPerformed
        JFileChooser ch = new JFileChooser();
        ch.setDialogType(JFileChooser.OPEN_DIALOG);
        ch.setFileSelectionMode(JFileChooser.FILES_ONLY);
        ch.setFileFilter(new VideoFileFilter());
        int val = ch.showOpenDialog(this);
        if(val != JFileChooser.APPROVE_OPTION) return;

        VideoLoadDialog d = null;
        try {
            d = new VideoLoadDialog(this, ch.getSelectedFile());
        }catch(IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, strings.getString("cantLoad"), strings.getString("loadError"), JOptionPane.ERROR_MESSAGE);
            return;
        }
        d.setVisible(true);

        ArrayList<FrameTile> result = d.getFrames();
        if(result == null) return;

        for(Tile ti : result) {
            t.addTile(ti);
        }
        label_step2count.setText(strings.getString("tileCount")+ t.getTiles().size());
        label_progress.setText(strings.getString("loadedFromVideo")+result.size());
    }//GEN-LAST:event_but_step2addVideoActionPerformed

    private void but_step2removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_step2removeActionPerformed
        t.removeTile(table_step2Preview.getSelectedRow(), table_step2Preview.getSelectedColumn());
        label_progress.setText(strings.getString("tileRemoved"));
        label_step2count.setText(strings.getString("tileCount") + t.getTiles().size());
    }//GEN-LAST:event_but_step2removeActionPerformed

    private void but_step2addFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_step2addFileActionPerformed
        // display file choose dialog and add file to tileset
        int retVal = openFileDialog.showOpenDialog(centralTabPane);
        if (retVal == JFileChooser.APPROVE_OPTION) {
            TileLoader worker = new TileLoader();
            worker.setFile(openFileDialog.getSelectedFile());
            worker.setTileset(t);
            worker.setUpdateLabel(label_progress);
            worker.setCountLabel(label_step2count);
            worker.setButton(but_step2addFile);
            but_step2addFile.setEnabled(false);
            label_progress.setText("");
            worker.execute();
        }
    }//GEN-LAST:event_but_step2addFileActionPerformed

    private void rb_selectRandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_selectRandActionPerformed
        if(rb_selectRand.isSelected()) m.setAlgorithm(SelectAlgorithm.RANDOM);
        box_avoidRep.setEnabled(rb_selectColor.isSelected());
    }//GEN-LAST:event_rb_selectRandActionPerformed

    private void rb_selectColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_selectColorActionPerformed
        if(rb_selectColor.isSelected()) m.setAlgorithm(SelectAlgorithm.COLOR);
        box_avoidRep.setEnabled(rb_selectColor.isSelected());
    }//GEN-LAST:event_rb_selectColorActionPerformed

    private void rb_selectMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_selectMatchActionPerformed
        if(rb_selectMatch.isSelected()) m.setAlgorithm(SelectAlgorithm.MATCH);
        box_avoidRep.setEnabled(rb_selectColor.isSelected());
    }//GEN-LAST:event_rb_selectMatchActionPerformed

    private void box_avoidRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_avoidRepActionPerformed
        m.setAvoidRep(box_avoidRep.isSelected());
    }//GEN-LAST:event_box_avoidRepActionPerformed

    private void rb_blendNoblendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_blendNoblendActionPerformed
        if(rb_blendNoblend.isSelected()) m.setBlend(Mosaic.Blend.NOBLEND);
        slider_blendAmount.setEnabled(rb_blendColor.isSelected() || rb_blendOriginal.isSelected());
    }//GEN-LAST:event_rb_blendNoblendActionPerformed

    private void rb_blendColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_blendColorActionPerformed
        if(rb_blendColor.isSelected()) m.setBlend(Mosaic.Blend.COLOR);
        slider_blendAmount.setEnabled(rb_blendColor.isSelected() || rb_blendOriginal.isSelected());
    }//GEN-LAST:event_rb_blendColorActionPerformed

    private void rb_blendOriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_blendOriginalActionPerformed
        if(rb_blendOriginal.isSelected()) m.setBlend(Mosaic.Blend.ORIGINAL);
        slider_blendAmount.setEnabled(rb_blendColor.isSelected() || rb_blendOriginal.isSelected());
    }//GEN-LAST:event_rb_blendOriginalActionPerformed

    private void but_step3saveSettActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_step3saveSettActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new MsfFileFilter());
        int result = chooser.showSaveDialog(this);
        if(result == JFileChooser.APPROVE_OPTION) {
            if(chooser.getSelectedFile().exists()) {
                int res = JOptionPane.showConfirmDialog(this, strings.getString("confirmOverwrite"), strings.getString("confirmTitle"), JOptionPane.YES_NO_OPTION);
                if(res != JOptionPane.YES_OPTION) return;
            }
            MosaicSettingIO.saveMosaic(chooser.getSelectedFile(), m);
            label_progress.setText(strings.getString("settingsSaved"));
        }
    }//GEN-LAST:event_but_step3saveSettActionPerformed

    private void but_step1loadSavedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_step1loadSavedActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new MsfFileFilter());
        int result = chooser.showOpenDialog(this);
        if(result == JFileChooser.APPROVE_OPTION) {
            this.m = MosaicSettingIO.loadMosaic(chooser.getSelectedFile());
            resetMosaic(m);
            label_progress.setText(strings.getString("settingsLoaded"));
        }
    }//GEN-LAST:event_but_step1loadSavedActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        this.but_step3saveSettActionPerformed(evt);
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.but_step3saveActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void but_step2removeAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_step2removeAllActionPerformed
        t.setTiles(new ArrayList<Tile>());
    }//GEN-LAST:event_but_step2removeAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the system look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhotomosaicWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhotomosaicWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhotomosaicWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhotomosaicWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        // load OpenCV
        try {
            System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        } catch(SecurityException | UnsatisfiedLinkError e) {
            Logger.getLogger(PhotomosaicWindow.class.getName()).log(Level.SEVERE, "Cannot load OpenCV library", e);
            JOptionPane.showMessageDialog(null, "Cannot load the OpenCV library", "Application can not start", JOptionPane.ERROR_MESSAGE);
            System.exit(-1);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhotomosaicWindow().setVisible(true);
            }
        });
    }

    private void paintGrid(int xTiles, int yTiles) {
        Mat res = m.getImg().clone();
        Point p1 = new Point(0, 0);
        Point p2 = new Point(0, 0);
        Scalar s = new Scalar(0,0,255);
        double xStep = m.getImg().width()/(double)m.getxTiles();
        double yStep = m.getImg().height()/(double)m.getyTiles();
        for(int i=0;i<xTiles;i++) {
            p1.x = i*xStep;
            p1.y = 0;
            p2.x = i*xStep;
            p2.y = res.height();
            Core.line(res, p1, p2, s);
        }
        for(int i=0;i<yTiles;i++) {
            p1.x = 0;
            p1.y = i*yStep;
            p2.x = res.width();
            p2.y = i*yStep;
            Core.line(res, p1, p2, s);
        }
        canvas.setImage(res);
        res.release();
    }
    
    private void resetMosaic(Mosaic m) {
        this.m = m;
        spin_xTiles.setValue(m.getxTiles());
        spin_yTiles.setValue(m.getyTiles());
        spin_tileWidth.setValue(m.getTileWidth());
        spin_tileHeight.setValue(m.getTileHeight());
        
        switch (m.getAlgorithm()) {
            case RANDOM:
                rb_selectRand.setSelected(true);
                break;
            case COLOR:
                rb_selectColor.setSelected(true);
                break;
            case MATCH:
                rb_selectMatch.setSelected(true);
                break;
        }
        box_avoidRep.setSelected(m.isAvoidRep());
        box_avoidRep.setEnabled(rb_selectColor.isSelected());
        
        switch(m.getBlend()) {
            case NOBLEND:
                rb_blendNoblend.setSelected(true);
                break;
            case COLOR:
                rb_blendColor.setSelected(true);
                break;
            case ORIGINAL:
                rb_blendOriginal.setSelected(true);
                break;
        }
        slider_blendAmount.setValue(m.getBlendAmount());
        slider_blendAmount.setEnabled(!rb_blendNoblend.isSelected());
    }

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if ("progress" == evt.getPropertyName()) {
            int prog = (int) evt.getNewValue();
            jProgressBar1.setValue(prog);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog aboutDialog;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.ButtonGroup blendBtnGrp;
    private javax.swing.JCheckBox box_avoidRep;
    private javax.swing.JButton but_step1browse;
    private javax.swing.JButton but_step1loadSaved;
    private javax.swing.JButton but_step1next;
    private javax.swing.JButton but_step2addFile;
    private javax.swing.JButton but_step2addFolder;
    private javax.swing.JButton but_step2addVideo;
    private javax.swing.JButton but_step2next;
    private javax.swing.JButton but_step2remove;
    private javax.swing.JButton but_step2removeAll;
    private javax.swing.JButton but_step3preview;
    private javax.swing.JButton but_step3save;
    private javax.swing.JButton but_step3saveSett;
    private javax.swing.JTabbedPane centralTabPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel label_progress;
    private javax.swing.JLabel label_step1preview;
    private javax.swing.JLabel label_step2count;
    private javax.swing.ButtonGroup matchingButGrp;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JFileChooser openDirDialog;
    private javax.swing.JFileChooser openFileDialog;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JRadioButton rb_blendColor;
    private javax.swing.JRadioButton rb_blendNoblend;
    private javax.swing.JRadioButton rb_blendOriginal;
    private javax.swing.JRadioButton rb_selectColor;
    private javax.swing.JRadioButton rb_selectMatch;
    private javax.swing.JRadioButton rb_selectRand;
    private javax.swing.JFileChooser saveFileDialog;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JScrollPane scrollPane_step2preview;
    private javax.swing.JSlider slider_blendAmount;
    private javax.swing.JSpinner spin_tileHeight;
    private javax.swing.JSpinner spin_tileWidth;
    private javax.swing.JSpinner spin_xTiles;
    private javax.swing.JSpinner spin_yTiles;
    private javax.swing.JPanel step1panel;
    private javax.swing.JPanel step2panel;
    private javax.swing.JPanel step3panel;
    private javax.swing.JTable table_step2Preview;
    // End of variables declaration//GEN-END:variables

}
